// <auto-generated />
using System;
using CustomerFluent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerFluent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250706130035_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerFluent.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("Floor")
                        .HasColumnType("tinyint");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblBuilding_LocationId");

                    b.ToTable("tblBuilding", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblBuilding_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblBuilding_ApartmentNumber", "[ApartmentNumber] > 0");

                            t.HasCheckConstraint("CK_tblBuilding_BuildingNumber", "[BuildingNumber] > 0");

                            t.HasCheckConstraint("CK_tblBuilding_Floor", "[Floor] BETWEEN 0 AND 200");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CustomerFluent.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_tblCustomer_Name");

                    b.ToTable("tblCustomer", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblCustomer_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblCustomer_Age", "[Age] BETWEEN 1 AND 120");

                            t.HasCheckConstraint("CK_tblCustomer_Height", "[Height] BETWEEN 50.0 AND 250.0");

                            t.HasCheckConstraint("CK_tblCustomer_Name", "LEN(LTRIM(RTRIM([Name]))) >= 2");

                            t.HasCheckConstraint("CK_tblCustomer_Phone", "[PhoneNumber] LIKE '+20[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR [PhoneNumber] LIKE '+20[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR [PhoneNumber] LIKE '01[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR [PhoneNumber] LIKE '0[2-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_tblCustomer_Weight", "[Weight] BETWEEN 2.0 AND 300.0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CustomerFluent.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblHouse_LocationId");

                    b.ToTable("tblHouse", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblHouse_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblHouse_HouseNumber", "[HouseNumber] > 0 AND [HouseNumber] <= 999999");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CustomerFluent.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("مصر");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblLocation_CustomerId");

                    b.HasIndex("Country", "City")
                        .HasDatabaseName("IX_tblLocation_Country_City");

                    b.ToTable("tblLocation", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblLocation_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblLocation_City", "LEN(LTRIM(RTRIM([City]))) >= 2");

                            t.HasCheckConstraint("CK_tblLocation_Country", "LEN(LTRIM(RTRIM([Country]))) > 0");

                            t.HasCheckConstraint("CK_tblLocation_Street", "LEN(LTRIM(RTRIM([Street]))) >= 3");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CustomerFluent.Models.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountRemaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_tblPaymentStatus_CustomerId");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_tblPaymentStatus_PaymentDate");

                    b.ToTable("tblPaymentStatus", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblPaymentStatus_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblPaymentStatus_AmountPaid", "[AmountPaid] >= 0");

                            t.HasCheckConstraint("CK_tblPaymentStatus_AmountRemaining", "[AmountRemaining] >= 0");

                            t.HasCheckConstraint("CK_tblPaymentStatus_MaxAmount", "[AmountPaid] <= 99999999.99 AND [AmountRemaining] <= 99999999.99");

                            t.HasCheckConstraint("CK_tblPaymentStatus_TotalAmount", "[AmountPaid] + [AmountRemaining] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CustomerFluent.Models.Building", b =>
                {
                    b.HasOne("CustomerFluent.Models.Location", "Location")
                        .WithOne("Building")
                        .HasForeignKey("CustomerFluent.Models.Building", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBuilding_Location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CustomerFluent.Models.House", b =>
                {
                    b.HasOne("CustomerFluent.Models.Location", "Location")
                        .WithOne("House")
                        .HasForeignKey("CustomerFluent.Models.House", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblHouse_Location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CustomerFluent.Models.Location", b =>
                {
                    b.HasOne("CustomerFluent.Models.Customer", "Customer")
                        .WithOne("Location")
                        .HasForeignKey("CustomerFluent.Models.Location", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblLocation_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerFluent.Models.PaymentStatus", b =>
                {
                    b.HasOne("CustomerFluent.Models.Customer", "Customer")
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPaymentStatus_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerFluent.Models.Customer", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("PaymentStatuses");
                });

            modelBuilder.Entity("CustomerFluent.Models.Location", b =>
                {
                    b.Navigation("Building");

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
