// <auto-generated />
using System;
using CustomerFluent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerFluent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250708121823_CompleteReset")]
    partial class CompleteReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerFluent.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int")
                        .HasComment("Apartment number on the floor");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int")
                        .HasComment("Building number on the street");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("Floor")
                        .HasColumnType("tinyint")
                        .HasComment("Floor number (0=Ground, 1-200=Upper floors)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblBuilding_LocationId");

                    b.HasIndex("BuildingNumber", "Floor", "ApartmentNumber")
                        .HasDatabaseName("IX_tblBuilding_Complete_Address");

                    b.ToTable("tblBuilding", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblBuilding_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblBuilding_ApartmentNumber", "[ApartmentNumber] BETWEEN 1 AND 999");

                            t.HasCheckConstraint("CK_tblBuilding_BuildingNumber", "[BuildingNumber] BETWEEN 1 AND 9999");

                            t.HasCheckConstraint("CK_tblBuilding_Floor", "[Floor] BETWEEN 0 AND 50");

                            t.HasCheckConstraint("CK_tblBuilding_Floor_Apartment_Logic", "([Floor] = 0 AND [ApartmentNumber] BETWEEN 1 AND 20) OR ([Floor] > 0 AND [ApartmentNumber] BETWEEN 1 AND 10)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentNumber = 8,
                            BuildingNumber = 15,
                            CreatedDate = new DateTime(2024, 2, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Floor = (byte)3,
                            LocationId = 2,
                            ModifiedDate = new DateTime(2024, 2, 10, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ApartmentNumber = 5,
                            BuildingNumber = 88,
                            CreatedDate = new DateTime(2024, 3, 5, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            Floor = (byte)7,
                            LocationId = 3,
                            ModifiedDate = new DateTime(2024, 3, 5, 9, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ApartmentNumber = 4,
                            BuildingNumber = 33,
                            CreatedDate = new DateTime(2024, 4, 12, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Floor = (byte)2,
                            LocationId = 5,
                            ModifiedDate = new DateTime(2024, 4, 12, 11, 40, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CustomerFluent.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint")
                        .HasComment("Age in years (must be between 16-120)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Record creation timestamp");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Height in centimeters");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Last modification timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Full name of the customer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComment("Phone number in Egyptian format");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Weight in kilograms");

                    b.HasKey("Id");

                    b.HasIndex("Age")
                        .HasDatabaseName("IX_tblCustomer_Age");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_tblCustomer_Name");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_tblCustomer_PhoneNumber");

                    b.ToTable("tblCustomer", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblCustomer_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblCustomer_Age", "[Age] BETWEEN 16 AND 120");

                            t.HasCheckConstraint("CK_tblCustomer_BMI_Logic", "([Weight] / POWER([Height]/100.0, 2)) BETWEEN 10.0 AND 60.0");

                            t.HasCheckConstraint("CK_tblCustomer_Height", "[Height] BETWEEN 100.0 AND 250.0");

                            t.HasCheckConstraint("CK_tblCustomer_Name", "LEN(LTRIM(RTRIM([Name]))) >= 2 AND [Name] NOT LIKE '%[0-9]%'");

                            t.HasCheckConstraint("CK_tblCustomer_Phone", "LEN([PhoneNumber]) >= 10 AND LEN([PhoneNumber]) <= 15");

                            t.HasCheckConstraint("CK_tblCustomer_Weight", "[Weight] BETWEEN 20.0 AND 500.0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = (byte)28,
                            CreatedDate = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Height = 175.50m,
                            ModifiedDate = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "أحمد محمد علي",
                            PhoneNumber = "+201234567890",
                            Weight = 75.20m
                        },
                        new
                        {
                            Id = 2,
                            Age = (byte)25,
                            CreatedDate = new DateTime(2024, 2, 10, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            Height = 162.00m,
                            ModifiedDate = new DateTime(2024, 2, 10, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            Name = "فاطمة حسن محمود",
                            PhoneNumber = "01098765432",
                            Weight = 58.50m
                        },
                        new
                        {
                            Id = 3,
                            Age = (byte)35,
                            CreatedDate = new DateTime(2024, 3, 5, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Height = 180.25m,
                            ModifiedDate = new DateTime(2024, 3, 5, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "محمد أحمد صالح",
                            PhoneNumber = "+201555123456",
                            Weight = 82.75m
                        },
                        new
                        {
                            Id = 4,
                            Age = (byte)22,
                            CreatedDate = new DateTime(2024, 3, 20, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Height = 165.75m,
                            ModifiedDate = new DateTime(2024, 3, 20, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "مريم عبد الله",
                            PhoneNumber = "01012345678",
                            Weight = 55.30m
                        },
                        new
                        {
                            Id = 5,
                            Age = (byte)42,
                            CreatedDate = new DateTime(2024, 4, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Height = 178.00m,
                            ModifiedDate = new DateTime(2024, 4, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "خالد إبراهيم",
                            PhoneNumber = "+201777888999",
                            Weight = 88.00m
                        });
                });

            modelBuilder.Entity("CustomerFluent.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int")
                        .HasComment("House number on the street");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("HouseNumber")
                        .HasDatabaseName("IX_tblHouse_HouseNumber");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblHouse_LocationId");

                    b.ToTable("tblHouse", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblHouse_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblHouse_HouseNumber", "[HouseNumber] BETWEEN 1 AND 9999");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 15, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            HouseNumber = 25,
                            LocationId = 1,
                            ModifiedDate = new DateTime(2024, 1, 15, 10, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 20, 16, 55, 0, 0, DateTimeKind.Unspecified),
                            HouseNumber = 142,
                            LocationId = 4,
                            ModifiedDate = new DateTime(2024, 3, 20, 16, 55, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CustomerFluent.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("CustomerFluent.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("CustomerFluent.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("City or governorate name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("مصر")
                        .HasComment("Country name (default: Egypt)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("True for house, False for apartment building");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Street address details");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblLocation_CustomerId");

                    b.HasIndex("IsHouse")
                        .HasDatabaseName("IX_tblLocation_IsHouse");

                    b.HasIndex("Country", "City")
                        .HasDatabaseName("IX_tblLocation_Country_City");

                    b.ToTable("tblLocation", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblLocation_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblLocation_City", "LEN(LTRIM(RTRIM([City]))) >= 2 AND [City] NOT LIKE '%[0-9]%'");

                            t.HasCheckConstraint("CK_tblLocation_Country", "LEN(LTRIM(RTRIM([Country]))) >= 2");

                            t.HasCheckConstraint("CK_tblLocation_Street", "LEN(LTRIM(RTRIM([Street]))) >= 5");

                            t.HasCheckConstraint("CK_tblLocation_Street_Content", "[Street] LIKE '%شارع%' OR [Street] LIKE '%ش.%' OR [Street] LIKE '%Street%' OR [Street] LIKE '%St.%' OR [Street] LIKE '%Avenue%' OR [Street] LIKE '%Road%' OR [Street] LIKE '%طريق%' OR LEN([Street]) >= 10");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "القاهرة",
                            Country = "مصر",
                            CreatedDate = new DateTime(2024, 1, 15, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            IsHouse = true,
                            ModifiedDate = new DateTime(2024, 1, 15, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            Street = "شارع النصر، مدينة نصر"
                        },
                        new
                        {
                            Id = 2,
                            City = "الإسكندرية",
                            Country = "مصر",
                            CreatedDate = new DateTime(2024, 2, 10, 14, 25, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            IsHouse = false,
                            ModifiedDate = new DateTime(2024, 2, 10, 14, 25, 0, 0, DateTimeKind.Unspecified),
                            Street = "شارع الحرية، محطة الرمل"
                        },
                        new
                        {
                            Id = 3,
                            City = "الجيزة",
                            Country = "مصر",
                            CreatedDate = new DateTime(2024, 3, 5, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            IsHouse = false,
                            ModifiedDate = new DateTime(2024, 3, 5, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            Street = "شارع الهرم، الطالبية"
                        },
                        new
                        {
                            Id = 4,
                            City = "القاهرة",
                            Country = "مصر",
                            CreatedDate = new DateTime(2024, 3, 20, 16, 50, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            IsHouse = true,
                            ModifiedDate = new DateTime(2024, 3, 20, 16, 50, 0, 0, DateTimeKind.Unspecified),
                            Street = "شارع التحرير، وسط البلد"
                        },
                        new
                        {
                            Id = 5,
                            City = "المنصورة",
                            Country = "مصر",
                            CreatedDate = new DateTime(2024, 4, 12, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            IsHouse = false,
                            ModifiedDate = new DateTime(2024, 4, 12, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            Street = "شارع الجمهورية، وسط المدينة"
                        });
                });

            modelBuilder.Entity("CustomerFluent.Models.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Amount already paid by customer");

                    b.Property<decimal>("AmountRemaining")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Remaining amount to be paid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Date of payment transaction");

                    b.HasKey("Id");

                    b.HasIndex("AmountRemaining")
                        .HasDatabaseName("IX_tblPaymentStatus_AmountRemaining");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_tblPaymentStatus_CustomerId");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_tblPaymentStatus_PaymentDate");

                    b.HasIndex("CustomerId", "PaymentDate")
                        .HasDatabaseName("IX_tblPaymentStatus_Customer_Date");

                    b.ToTable("tblPaymentStatus", "dbo", t =>
                        {
                            t.HasTrigger("TR_tblPaymentStatus_UpdateModifiedDate");

                            t.HasCheckConstraint("CK_tblPaymentStatus_AmountPaid", "[AmountPaid] >= 1.00");

                            t.HasCheckConstraint("CK_tblPaymentStatus_AmountRemaining", "[AmountRemaining] >= 0");

                            t.HasCheckConstraint("CK_tblPaymentStatus_MaxAmount", "[AmountPaid] <= 99999999.99 AND [AmountRemaining] <= 99999999.99");

                            t.HasCheckConstraint("CK_tblPaymentStatus_PaymentDate", "[PaymentDate] <= GETDATE()");

                            t.HasCheckConstraint("CK_tblPaymentStatus_TotalAmount", "[AmountPaid] + [AmountRemaining] >= 1.00");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 5000.00m,
                            AmountRemaining = 15000.00m,
                            CreatedDate = new DateTime(2024, 1, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ModifiedDate = new DateTime(2024, 1, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 1, 20, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 3000.00m,
                            AmountRemaining = 12000.00m,
                            CreatedDate = new DateTime(2024, 2, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ModifiedDate = new DateTime(2024, 2, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 2, 15, 10, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AmountPaid = 8500.50m,
                            AmountRemaining = 6500.50m,
                            CreatedDate = new DateTime(2024, 2, 25, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            ModifiedDate = new DateTime(2024, 2, 25, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 2, 25, 16, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AmountPaid = 12000.75m,
                            AmountRemaining = 8000.25m,
                            CreatedDate = new DateTime(2024, 3, 10, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            ModifiedDate = new DateTime(2024, 3, 10, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 3, 10, 11, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AmountPaid = 2500.00m,
                            AmountRemaining = 7500.00m,
                            CreatedDate = new DateTime(2024, 3, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            ModifiedDate = new DateTime(2024, 3, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 3, 25, 13, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AmountPaid = 18000.00m,
                            AmountRemaining = 0.00m,
                            CreatedDate = new DateTime(2024, 4, 15, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            ModifiedDate = new DateTime(2024, 4, 15, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 4, 15, 15, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "dbo");
                });

            modelBuilder.Entity("CustomerFluent.Models.Building", b =>
                {
                    b.HasOne("CustomerFluent.Models.Location", "Location")
                        .WithOne("Building")
                        .HasForeignKey("CustomerFluent.Models.Building", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBuilding_Location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CustomerFluent.Models.House", b =>
                {
                    b.HasOne("CustomerFluent.Models.Location", "Location")
                        .WithOne("House")
                        .HasForeignKey("CustomerFluent.Models.House", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblHouse_Location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CustomerFluent.Models.Location", b =>
                {
                    b.HasOne("CustomerFluent.Models.Customer", "Customer")
                        .WithOne("Location")
                        .HasForeignKey("CustomerFluent.Models.Location", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblLocation_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerFluent.Models.PaymentStatus", b =>
                {
                    b.HasOne("CustomerFluent.Models.Customer", "Customer")
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPaymentStatus_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CustomerFluent.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CustomerFluent.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CustomerFluent.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("CustomerFluent.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerFluent.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CustomerFluent.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerFluent.Models.Customer", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("PaymentStatuses");
                });

            modelBuilder.Entity("CustomerFluent.Models.Location", b =>
                {
                    b.Navigation("Building");

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
